@startuml
left to right direction
skinparam classAttributeAlignment left

class AuditoriaController {
  - AuditoriaRepository repository
  + AuditoriaController(AuditoriaRepository)
  + ResponseEntity<List<Auditoria>> listar()
}

note top of AuditoriaController
  Package: pe.aspropa.mercadolink.controller
end note

@enduml