@startuml
left to right direction
skinparam classAttributeAlignment left

class AuthController {
  - AuthService authService
  - ActorService actorService
  + AuthController(AuthService, ActorService)
  + ResponseEntity<LoginResponse> login(LoginRequest)
  + ResponseEntity<Map<String, Object>> register(RegisterRequest)
}

note top of AuthController
  Package: pe.aspropa.mercadolink.controller
end note

@enduml