@startuml
left to right direction
skinparam classAttributeAlignment left
class EstadoFisico <<Enumeration>> {
  BUENO
  DETERIORADO
  VENCIDO
}
note top of EstadoFisico
  Package: pe.aspropa.mercadolink.domain
end note
@enduml
