@startuml
left to right direction
skinparam classAttributeAlignment left
class Puesto <<Entity>> {
  {field} private String id
  {field} private String nombre
  {field} private String numero
  {field} private String seccion
  {field} private boolean activo
  {method} public String getId()
  {method} public void setId(String id)
  {method} public String getNombre()
  {method} public void setNombre(String nombre)
  {method} public String getNumero()
  {method} public void setNumero(String numero)
  {method} public String getSeccion()
  {method} public void setSeccion(String seccion)
  {method} public boolean isActivo()
  {method} public void setActivo(boolean activo)
}
note top of Puesto
  Package: pe.aspropa.mercadolink.domain
end note
@enduml
