@startuml
left to right direction
skinparam classAttributeAlignment left

class IzipayWebhookRequest << (T,#FFAAAA) >> {
  {field} private String orderId
  {field} private String transactionId
  {field} private String status
  {field} private String amount
  {field} private String signature
  {method} public String getOrderId()
  {method} public void setOrderId(String)
  {method} public String getTransactionId()
  {method} public void setTransactionId(String)
  {method} public String getStatus()
  {method} public void setStatus(String)
  {method} public String getAmount()
  {method} public void setAmount(String)
  {method} public String getSignature()
  {method} public void setSignature(String)
}

note top of IzipayWebhookRequest
  Package: pe.aspropa.mercadolink.dto
end note

@enduml